theme: jekyll-theme-cayman
title: Timor-Leste Pride Parade
description: The 2018 Timor-Leste pride parade will take place on July 20th in Dili. It is organised by Hatutan, CODIVA, Arco Iris and other partners.
github:
    is_project_page: false
email: hatutanyouth@gmail.com
